language: python
fast_finish: true

python:
  - 2.7

os:
  - linux

sudo: required
dist: trusty
group: edge

addons:
  apt:
    packages: ['dbus-x11','xvfb','libdbus-1-dev','libdbus-glib-1-dev','geoclue','geoclue-ubuntu-geoip']

notifications:
  email: false

git:
  depth: 3


before_install:
  - pip -q install coveralls

install: pip install -e .

before_script:
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: sudo coverage run tests/test.py -v

after_success: coveralls
